---
- name: Include role variables
  ansible.builtin.include_tasks: "include_vars.yml"
  tags:
    - always
  loop:
    - "{{ ansible_os_family }}.yml" # e.g. Debian for ubuntu and debian
  loop_control:
    loop_var: vars_file

- name: Configure apt
  ansible.builtin.include_tasks:
    file: configure-apt/main.yml
    apply:
      tags:
        - configure-apt
  tags:
    - configure-apt

- name: Configure sendmail
  ansible.builtin.include_tasks:
    file: sendmail/main.yml
    apply:
      tags:
        - sendmail
  tags:
    - sendmail
