---
- name: Include role variables
  ansible.builtin.include_tasks: "include_vars.yml"
  tags:
    - always
  loop:
    - "{{ ansible_os_family }}.yml" # e.g. Debian for ubuntu and debian
  loop_control:
    loop_var: vars_file

- name: Install updates
  ansible.builtin.include_tasks:
    file: apt-update/main.yml
    apply:
      tags:
        - apt-update
  tags:
    - apt-update

- name: Configure server services
  ansible.builtin.include_tasks:
    file: server-services/main.yml
    apply:
      tags:
        - configure-server-services
  tags:
    - configure-server-services

- name: Configure external drives
  ansible.builtin.include_tasks:
    file: external-drives/main.yml
    apply:
      tags:
        - configure-external-drives
  when: boolean_base_external_drives
  tags:
    - configure-external-drives

- name: Configure dropbear
  ansible.builtin.include_tasks:
    file: dropbear/main.yml
    apply:
      tags:
        - configure-dropbear
  when: boolean_base_dropbear
  tags:
    - configure-dropbear