---
- name: Include role variables
  ansible.builtin.include_tasks: "include_vars.yml"
  tags:
    - always
  loop:
    - "{{ ansible_os_family }}.yml" # e.g. Debian for ubuntu and debian
  loop_control:
    loop_var: vars_file

- name: Führe apt update aus
  ansible.builtin.package:
    update_cache: yes

- name: Führe apt upgrade -y aus
  ansible.builtin.package:
    upgrade: dist

- name: Install onboarding packages
  ansible.builtin.package:
    name: "{{ list_onboarding_packages }}"
    state: latest
    update_cache: yes

- name: Configure ssh access
  ansible.builtin.include_tasks:
    file: configure-ssh/main.yml
    apply:
      tags:
        - configure-ssh
  tags:
    - configure-ssh