---
- name: Include role variables
  ansible.builtin.include_tasks: "include_vars.yml"
  tags:
    - always
  loop:
    - "{{ ansible_os_family }}.yml" # e.g. Debian for ubuntu and debian
  loop_control:
    loop_var: vars_file

- name: Configure apt
  ansible.builtin.include_tasks:
    file: apt/main.yml
    apply:
      tags:
        - apt
  tags:
    - apt

- name: Install onboarding packages
  ansible.builtin.package:
    name: "{{ list_onboarding_packages }}"
    state: latest
    update_cache: yes

- name: Configure ssh access
  ansible.builtin.include_tasks:
    file: configure-ssh/main.yml
    apply:
      tags:
        - configure-ssh
  tags:
    - configure-ssh

- name: Install improvements
  ansible.builtin.include_tasks:
    file: improvements/main.yml
    apply:
      tags:
        - improvements
  tags:
    - improvements

- name: Configure sendmail
  ansible.builtin.include_tasks:
    file: sendmail/main.yml
    apply:
      tags:
        - sendmail
  tags:
    - sendmail