---
# vars here
list_onboarding_packages:
  - sudo
  - python-is-python3
  - htop
  - nano
  - needrestart

list_onboarding_sendmail_packages:
  - msmtp
  - msmtp-mta
  - bsd-mailx

list_onboarding_locales_default_locales:
  - de_DE.UTF-8
  - en_US.UTF-8
