---
# vars here
list_onboarding_packages:
  - sudo
  - python-is-python3
  - htop
  - nano

list_onboarding_unattended_upgrade_packages:
  - unattended-upgrades
  - needrestart

list_onboarding_sendmail_packages:
  - msmtp
  - msmtp-mta
  - bsd-mailx