---
# vars here
list_docker_install_dependencies:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

boolean_docker_watchtower_enabled: false
# both, notify, updates
# str_docker_watchtower_mode: notify