---
- name: Copy nginx site configurations
  ansible.builtin.template:
    src: "etc/nginx/sites-available/{{ item }}.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
    owner: root
    group: root
    mode: "0640"
  loop: "{{ nginx_sites }}"

- name: Enable nginx sites
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
    state: link
  loop: "{{ nginx_sites }}"
  notify: reload nginx