---
- name: Update and upgrade packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Install unattended upgrades packages
  ansible.builtin.package:
    name: "{{ list_base_unattended_upgrades }}"
    state: present

- name: create unattended-upgrades configuration
  ansible.builtin.template:
    src: etc/apt/apt.conf.d/52unattended-upgrades-local.j2
    dest: /etc/apt/apt.conf.d/52unattended-upgrades-local
    owner: root
    group: root
    mode: "0640"