---
boolean_docker_watchtower_enabled: true
str_docker_watchtower_mode: "notify"
str_docker_watchtower_hostname: "immich"

list_docker_compose_apps:
  - name: immich
    compose_files:
      - src: opt/immich/docker-compose.yml.j2
      - src: opt/immich/.env.j2