---
boolean_docker_watchtower_enabled: false
str_docker_watchtower_mode: "notify"
str_docker_watchtower_hostname: "nextcloud"

list_docker_compose_apps:
  - name: nextcloud
    compose_files:
      - src: opt/nextcloud/docker-compose.yml.j2
  - name: arcane-agent
    compose_files:
      - src: opt/arcane-agent/docker-compose.yml.j2

str_docker_compose_arcane_agent_token: "{{ cstr_docker_compose_arcane_agent_nextcloud_token }}"