---
- name: Check if Docker is installed
  ansible.builtin.command: docker -v 
  register: docker_installed
  ignore_errors: true

- name: Install necessary packages for docker
  ansible.builtin.package:
    name:
      - ca-certificates 
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to Apt sources
  ansible.builtin.template:
    src: etc/apt/sources.list.d/docker.sources.j2
    dest: /etc/apt/sources.list.d/docker.sources
    owner: root
    group: root
    mode: '0644'

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present
    update_cache: true
  when: docker_installed.failed

- name: Ensure Docker group exists
  become: yes
  ansible.builtin.group:
    name: docker
    state: present
  register: docker_group

- name: Add User to docker group
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker 
    append: true 
  when: docker_group is changed

- name: Start and enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: docker_installed.failed