---
- name: Ensure jellyfin compose dir exists
  ansible.builtin.file:
    path: /opt/docker-compose/jellyfin
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy jellyfin docker-compose file
  ansible.builtin.template:
    src: opt/docker-compose/jellyfin/docker-compose.yml.j2
    dest: /opt/docker-compose/jellyfin/docker-compose.yml
    group: root
    owner: root
    mode: "0644"

- name: Include webserver-specific tasks
  ansible.builtin.include_tasks: "{{ str_webserver_engine }}.yml"