---
- name: Copy nginx immich.tgotowik.de.conf
  ansible.builtin.template:
    src: etc/nginx/sites-available/immich.tgotowik.de.conf.local.j2
    dest: /etc/nginx/sites-available/immich.tgotowik.de.conf
    owner: root
    group: root
    mode: "0640"

- name: Enable site immich.tgotowik.de
  ansible.builtin.file:
    src: /etc/nginx/sites-available/immich.tgotowik.de.conf
    dest: /etc/nginx/sites-enabled/immich.tgotowik.de.conf
    state: link
  notify: restart nginx