[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=/home/tgotowik/.ssh/id_homeserver
ansible_become=true

[all]
pve           ansible_host=192.168.178.55 ansible_ssh_private_key_file=/home/tgotowik/.ssh/id_pve
webserver     ansible_host=192.168.178.100
pihole        ansible_host=192.168.178.101
vaultwarden   ansible_host=192.168.178.110
immich        ansible_host=192.168.178.111
jellyfin      ansible_host=192.168.178.112
nextcloud     ansible_host=192.168.178.113
paperless     ansible_host=192.168.178.115

[all_ansible_vms]
webserver
pihole
vaultwarden
immich
jellyfin
nextcloud
paperless

[all_ansible_docker]
pihole
vaultwarden
immich
jellyfin
nextcloud
paperless