[all:vars]
ansible_user=tgotowik
ansible_ssh_private_key_file=/home/tgotowik/.ssh/id_homeserver
ansible_become=true

[all]
192.168.178.83
192.168.178.84

[vaultwarden]
192.168.178.83

[immich]
192.168.178.84