---
- name: Install base server services
  ansible.builtin.package:
    name: "{{ list_base_server_services }}"

- name: Copy msmtp config
  ansible.builtin.template:
    src: etc/msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: "0600"