---
- name: Install webserver packages
  ansible.builtin.package:
    name: "{{ list_webserver_apache_packages }}"
    state: present
    update_cache: true

- name: Enable required Apache modules
  ansible.builtin.command: a2enmod proxy proxy_http ssl headers rewrite
  notify: restart apache

- name: Deploy Apache vhost for proxy
  ansible.builtin.template:
    src: etc/apache2/sites-available/proxy_vhost.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: restart apache