---
- name: Copy nginx nas.tgotowik.de.conf
  ansible.builtin.template:
    src: etc/nginx/sites-available/nas.tgotowik.de.conf.j2
    dest: /etc/nginx/sites-available/nas.tgotowik.de.conf
    owner: root
    group: root
    mode: "0640"
  notify: restart nginx

- name: Enable site nas.tgotowik.de
  ansible.builtin.file:
    src: /etc/nginx/sites-available/nas.tgotowik.de.conf
    dest: /etc/nginx/sites-enabled/nas.tgotowik.de.conf
    state: link
  notify: restart nginx