- name: Copy ha.tgotowik.de.conf
  ansible.builtin.template:
    src: etc/nginx/sites-available/ha.tgotowik.de.conf.j2
    dest: /etc/nginx/sites-available/ha.tgotowik.de.conf
    owner: root
    group: root
    mode: "0640"

- name: Enable site ha.tgotowik.de
  ansible.builtin.file:
    src: /etc/nginx/sites-available/ha.tgotowik.de.conf
    dest: /etc/nginx/sites-enabled/ha.tgotowik.de.conf
    state: link
  notify: restart nginx