---
- name: Ensure minecraft compose dir exists
  ansible.builtin.file:
    path: /opt/docker-compose/minecraft
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy minecraft docker-compose file
  ansible.builtin.template:
    src: opt/docker-compose/minecraft/docker-compose.yml.j2
    dest: /opt/docker-compose/minecraft/docker-compose.yml
    group: root
    owner: root
    mode: "0644"

- name: Ensure minecraft assets dir exists
  ansible.builtin.file:
    path: /opt/docker-compose/minecraft/assets
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy minecraft server icon
  ansible.builtin.copy:
    src: opt/docker-compose/minecraft/assets/icon.png
    dest: /opt/docker-compose/minecraft/assets/icon.png
    owner: root
    group: root
    mode: "0644"