---
- name: Include role variables
  ansible.builtin.include_tasks: "include_vars.yml"
  tags:
    - always
  loop:
    - "{{ ansible_os_family }}.yml" # e.g. Debian for ubuntu and debian
  loop_control:
    loop_var: vars_file

- name: Configure pihole
  ansible.builtin.include_tasks:
    file: pihole/main.yml
    apply:
      tags:
        - pihole
  tags:
    - pihole
