---
- name: Install ntfs
  ansible.builtin.package:
    name: ntfs-3g
    state: present

- name: Create nas mnt dir
  ansible.builtin.file:
    path: /mnt/Drive
    state: directory
    mode: "0755"

- name: Deploy nas_disk systemd service
  ansible.builtin.template:
    src: etc/systemd/system/nas_disk.service.j2
    dest: /etc/systemd/system/nas_disk.service
    owner: root
    group: root
    mode: "0644"

- name: Ensure nas_disk service is enabled and running
  ansible.builtin.service:
    name: nas_disk
    enabled: true
    state: started

- name: Create backup mnt dir
  ansible.builtin.file:
    path: /mnt/Backup
    state: directory
    mode: "0755"

- name: Copy backup service file
  ansible.builtin.template:
    src: etc/systemd/system/backup_disk.service.j2
    dest: /etc/systemd/system/backup_disk.service
    owner: root
    group: root
    mode: "0644"
  notify: reload backup disk

- name: Ensure backup_disk service is enabled and running
  ansible.builtin.service:
    name: backup_disk
    enabled: true
    state: started
