---
- name: Docker 
  hosts: all_ansible_docker
  tags: docker
  roles:
    - docker

- name: Deploy docker compose apps
  hosts: all_ansible_docker
  tags: docker-compose
  roles:
    - docker-compose

- name: Install nginx
  hosts: webserver
  tags: nginx
  roles:
    - nginx

- name: Install pve
  hosts: pve
  vars:
    ansible_user: root
  tags: pve
  roles:
    - pve

- name: Install onboard
  hosts: all
  tags: onboard
  roles:
    - onboard

- name: Install minecraft
  hosts: minecraft
  tags: minecraft
  roles:
    - minecraft