---
- name: Onboarding
  hosts: all
  remote_user: root
  roles:
    - { role: onboard, tags: ['onboard', 'setup'] }

- name: All roles
  hosts: all
  become: true
  roles:
    - { role: base,    tags: ['base', 'setup'] }
    - { role: vaultwarden,  tags: ['vaultwarden'] }
    - { role: nextcloud,  tags: ['nextcloud'] }
    - { role: immich,  tags: ['immich'] }
    - { role: jellyfin,  tags: ['jellyfin'] }