---
- name: Include role variables
  ansible.builtin.include_tasks: "include_vars.yml"
  tags:
    - always
  loop:
    - "{{ ansible_os_family }}.yml" # e.g. Debian for ubuntu and debian
  loop_control:
    loop_var: vars_file

# - name: Install minecraft docker
#   ansible.builtin.include_tasks:
#     file: minecraft/main.yml
#     apply:
#       tags:
#         - minecraft
#   tags:
#     - minecraft