---
- name: Include role variables
  ansible.builtin.include_tasks: "include_vars.yml"
  tags:
    - always
  loop:
    - "{{ ansible_os_family }}.yml" # e.g. Debian for ubuntu and debian
  loop_control:
    loop_var: vars_file

- name: Install nginx
  ansible.builtin.include_tasks:
    file: nginx/main.yml
    apply:
      tags:
        - install-nginx
  tags:
    - install-nginx

- name: Configure sites-available
  ansible.builtin.include_tasks:
    file: sites-available/main.yml
    apply:
      tags:
        - sites-available
  tags:
    - sites-available