---
- name: Install sendmail packages
  ansible.builtin.package:
    name: "{{ list_onboarding_sendmail_packages }}"

- name: Copy msmtp config
  ansible.builtin.template:
    src: etc/msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: "0600"