---
- name: Install docker dependencies
  ansible.builtin.package:
    name: "{{ list_docker_install_dependencies }}"
    state: present
    update_cache: true

- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to Apt sources
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    state: present
    filename: Docker

- name: Install docker
  ansible.builtin.package:
    name: "{{ list_docker_packages }}"
    state: present
    update_cache: true

- name: Start and enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true